### ISSUE TITLE
Help Improve Accessibility

### ISSUE THREAD

**Issue by lauragift21** [lauragift21/gridsome-blog#9]
This project was created as an inspiration for an article and I think overall accessibility can be improved on in this project. 
If this is up your alley I'm happy to provide more context.

**Comment by brunopulis** [comment]
Hey @lauragift21 I can help you with a11y issues.

**Comment by lauragift21** [comment]
Hi @brunopulis Thanks for the help. 

Let me know if you need any help.

**Comment by brunopulis** [comment]
Hello @lauragift21 this week I will test the website and I show you the report about a11y and we implement the fixes for it.

**Comment by lauragift21** [comment]
Awesome that works!
